[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pension_chain = "BZsjYUuSohczPCTGFy4R1u9LAUHiAMtHEZfrsgMURQSV"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
