[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
pension_chain = "4ssu3jphFPGkmBqLkfADP48pSSvYq8rVoCSZVZtzfCHp"

[provider]
cluster = "devnet"
wallet = "/home/alex/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
